# Generated by Django 5.2.5 on 2025-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('project', 'Project'), ('ai-generated', 'ai-generated')], max_length=20),
        ),
    ]
